server:
  port: 9080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres 
    password: password
  mvc:
    format:
      date: yyyy-MM-dd
